Facts = [
  '$NAME is, when angry, over 40 metres tall.',
  '$NAME has quite an impressive collection of assorted cutlery, ranging back to the early Stuart period.',
  'No bully has ever mananged to quite get to $NAME.',
  '$NAME has on many occasions finished the entire meal, politely putting the knife and fork together before leaning back with a satisfied sigh.',
  'The very utterance of $NAME\'s name will bring terror to the heart of anyone in the Royal Family.',
  '$NAME once ran for president.',
  'Dogs trust $NAME.',
  '$NAME is prone to running around the house in a tiz at 4 AM.',
  'A tiger once challanged $NAME to a duel and lost. They are now firm friends.',
  'A whole class load of children once spotted $NAME riding a bicycle down the steepest hill in town.',
  'A wizard once turned $NAME into a whale.',
  '$NAME once made three beds for a new family of bears. One was firm, one was soft, and the last one was medium.',
  'A new class of battleships has been named $NAME',
  'Birds will not swoop $NAME. Instead, they drop small gifts. Anything bright will do: coloured beeds, insects, leaves, flowers, etc.',
  '$NAME can immitate any species of bird known to mankind, and a great deal that are not.',
  'It\'s hard not to like $NAME.',
  '$NAME has only ever eaten three bowls of porridge. One was too hot, one was too cold, but the last one was just right.',
  '$NAME once fought a website that was making stuff up.',
  '$NAME is allergic to lies.',
  '$NAME has been known to speak many languages, including Russian, English and The Ancient Tongue of the Tulips',
  '$NAME has no known vulnerabilities.',
  'It has been said that $NAME\'s face is the face that launched a thousand and one ships.',
  'No kind of hat will fit $NAME.',
  'Ducks can\'t see $NAME.',
  '$NAME invented a new kind of electric motor that when combined with high capacity storage will deliver minimal message-oriented transport layers with encrypted high security decoupling and save the world.',
  '$NAME sang the vocals in "The Great Gig In The Sky".',
  '$NAME can speak to cats.',
  '$NAME is not afraid of trains.',
  '$NAME can add up very large numbers while doing a guitar solo of \'Come all ye faithful\' with his teeth.',
  'After the tragic fire I was so distraught with the loss of my manuscript that $NAME  stayed up all night to recompose it from the leftover sheets, even correcting the spelling and corrected a plot hole in the wedding scene.',
  '$NAME once trained a bear to whistle, but it escaped.  The bear was only found by following the trail of destruction and a faint, feeble tune.',
  '$NAME once recorded a session with Pink Floyd. The guitar solo was so blistering that Roger Waters immediately ceremoniously burnt the tapes.',
  '$NAME spends a lot of spare time knitting, but never does gloves (the thumbs are too difficult).'
]